### ISSUE TITLE
add `ResponsiveImage` class definition

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.Publications#41]
📖 http://songhayblog.azurewebsites.net/entry/2020-08-30-studio-status-report-2020-08/

We have this rough sketch at the moment:

![image](https://user-images.githubusercontent.com/5226627/110429709-2cb1d600-8060-11eb-98ac-c65c9cecf050.png)

it is not clear (to me) whether these definitions and relations can support CSS as well as `img` with `srcset`

these classes need to support both

**Comment by BryanWilhite** [comment]
here is a CSS example we need to support:

```scss
body {
    /* background-image */
    @media only screen and (orientation: portrait) {
        background-image: url(https://songhaystorage.blob.core.windows.net/songhay-player/stills/responsive-test-index/index-720x1280.png);
    }

    /* 720x1280 => 1080x1920 */
    @media only screen and (min-width: $width-720x1280) and (orientation: portrait) {
        background-image: url(https://songhaystorage.blob.core.windows.net/songhay-player/stills/responsive-test-index/index-1080x1920.png);
    }

    @media only screen and (orientation: landscape) {
        background-image: url(https://songhaystorage.blob.core.windows.net/songhay-player/stills/responsive-test-index/index-720p.png);
    }

    /* 1080p => 1920w */
    @media only screen and (min-width: $width-720p) and (orientation: landscape) {
        background-image: url(https://songhaystorage.blob.core.windows.net/songhay-player/stills/responsive-test-index/index-1080p.png);
    }

    /* grid-template-columns */
    @media only screen and (min-width: $width-720x1280) {
        & > main {
            grid-template-columns: 1fr ($thumb-size * 2);

            & > aside {
                display: block;
            }
        }
    }

    @media only screen and (max-width: $width-720x1280) {
        & > main {
            grid-template-columns: minmax(min-content, 1fr);

            & > aside {
                display: none;
            }
        }
    }
}

```
